apiVersion: v1
kind: Pod
metadata:
  labels:	
    run: girus
    service: webserver
  name: girus
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: httpd
    name: apache
  dnsPolicy: ClusterFirst
  restartPolicy: Always
